version: '3'

services:
  mwdb:
    restart: always
    container_name: mwdb
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mediawiki
    volumes:
      - ./mariadb/mwup:/var/lib/mysql
      - ./import:/tmp/import

  mwup:
    image: tbd
    depends_on:
      - mwdb
    container_name: mwup
    environment:
      MEDIAWIKI_SERVER: transition
      MEDIAWIKI_DB_NAME: mediawiki
      MEDIAWIKI_DB_USER: root
      MEDIAWIKI_DB_PASSWORD: secret
      MEDIAWIKI_DB_HOST: mwdb
      MW_WG_DBUSER: root
      MW_WG_DBPASS: secret
      MW_WG_SERVER: transition
      MW_WG_DBNAME: mediawiki
      MW_WG_DBSERVER: mwdb
      MW_WG_SITENAME: transition
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    ports:
      - 8087:80

